name: AutoGest RD
description: "Solución integral móvil desarrollada en Flutter para la gestión inteligente de flotas vehiculares y finanzas personales."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets: 
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 